OSRM_URL = 'http://router.project-osrm.org/route/v1/driving'

MILE_IN_METERS = 1609.34
SECONDS_IN_HOUR = 3600
FUEL_STOP_DISTANCE = 1000 * MILE_IN_METERS
DAILY_DRIVING_LIMIT_HRS = 11
REQUIRED_BREAK_HRS_THRESHOLD = 8